"""
tests/test_ec2_login.py — Diagnostic tool for Cloud IP Bans & Bot Protection.

This script runs a headless Chromium browser using Playwright to attempt 
a standard Microsoft Teams web login. 

If it works: We can run the Playwright scraper directly on the EC2 server and abandon the BYOT architecture.
If it fails: Microsoft is likely throwing a CAPTCHA, "Suspicious Activity", or IP Block error because it detects a datacenter IP address.
"""

import os
import sys
import logging
from pathlib import Path
from dotenv import load_dotenv
from playwright.sync_api import sync_playwright

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("ec2_test")

# Load environment variables (from .env generated by deployment script)
load_dotenv(Path(__file__).parent.parent / ".env")

def run_test():
    email = os.getenv("EMAIL")
    password = os.getenv("PASSWORD")

    if not email or not password:
        log.error("❌ ERROR: EMAIL and PASSWORD must be set in your .env file.")
        sys.exit(1)

    log.info("=======================================================")
    log.info("🔍 DIAGNOSTIC: Testing Headless Login from Server IP")
    log.info("=======================================================\n")
    log.info("Attempting login for: %s", email)

    with sync_playwright() as p:
        # Must be headless on a Linux server without a display driver.
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()

        try:
            log.info("Navigating to login.microsoftonline.com...")
            page.goto("https://login.microsoftonline.com/", timeout=60000)
            
            # 1. Email Field
            log.info("Waiting for email field...")
            page.wait_for_selector('input[type="email"]', timeout=30000)
            page.fill('input[type="email"]', email)
            page.click('input[type="submit"]')

            # 2. Password Field
            log.info("Waiting for password field...")
            page.wait_for_selector('input[type="password"]', timeout=30000)
            page.fill('input[type="password"]', password)
            page.wait_for_timeout(1000) # Buffer for UI animations
            page.click('input[type="submit"]')
            
            # 3. Handle 'Stay signed in?' prompt if it appears
            try:
                log.info("Checking for 'Stay signed in?' prompt...")
                page.click('input[type="submit"]', timeout=5000)
            except Exception:
                pass

            # 4. Check Final URL / State
            log.info("Waiting for successful redirect into Microsoft portal...")
            page.wait_for_url("**/landing**", timeout=30000)
            
            log.info("\n✅ SUCCESS: Unbelievable! Microsoft allowed a headless login from an EC2 datacenter IP.")
            log.info("We can abandon the local BYOT script and run the extraction purely in the cloud.")
            
        except Exception as e:
            log.error("\n❌ FAILED: Microsoft blocked the headless login attempt.")
            log.error("Reason: %s", str(e))
            log.error("\nTaking a screenshot of the block screen for analysis...")
            
            # Save a screenshot so we can see *why* we got blocked (e.g. CAPTCHA, conditional access, IP ban)
            screenshot_path = Path(__file__).parent.parent / "ec2_block_screen.png"
            page.screenshot(path=str(screenshot_path))
            log.error("Screenshot saved to: %s", screenshot_path)
            log.error("This confirms we MUST use the BYOT (Bring Your Own Token) architecture.")
            
        finally:
            browser.close()

if __name__ == "__main__":
    run_test()
